services:
  - type: web
    name: student-collaboration-hub-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://student-collaboration-hub-backend.onrender.com/api 