#!/bin/bash

echo "🚀 Student Collaboration Hub Deployment Script"
echo "=============================================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. ✅ GitHub repository with your code"
echo "2. ✅ Render.com account (free)"
echo "3. ✅ MongoDB Atlas account (free)"
echo ""

echo "🔧 Backend Deployment Steps:"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: student-collaboration-hub-backend"
echo "   - Root Directory: backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "5. Add Environment Variables:"
echo "   - MONGO_URI: your_mongodb_connection_string"
echo "   - JWT_SECRET: your_secret_key"
echo "   - NODE_ENV: production"
echo ""

echo "🌐 Frontend Deployment Steps:"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Static Site'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: student-collaboration-hub-frontend"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: dist"
echo "5. Add Environment Variable:"
echo "   - VITE_API_URL: https://your-backend-name.onrender.com/api"
echo ""

echo "✅ After Deployment:"
echo "- Backend URL: https://student-collaboration-hub-backend.onrender.com"
echo "- Frontend URL: https://student-collaboration-hub-frontend.onrender.com"
echo "- Share the frontend URL with your professor!"
echo ""

echo "🔍 Test Commands:"
echo "curl https://your-backend-name.onrender.com/api/health"
echo ""

echo "📚 Need MongoDB Atlas?"
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create free account"
echo "3. Create cluster"
echo "4. Get connection string"
echo "5. Add to Render environment variables" 